### ISSUE TITLE
rerun failures argument is not properly parsing the failures.txt

### ISSUE THREAD

**Issue by kappa10j** [hrcorval/behavex#19] opened 2022-04-19 19:51 UTC
failures.txt contains one line: 

features/Create CHG/Different Tabs for different Change Categories.feature:14

calling behavex -rf considers spaces to mean there are different tests.

C:\Source\Repos\jira-automated-testing>behavex -rf
|--------------------| ------------------------------------------------------------|
|ENV. VARIABLE       | VALUE                                                       |
|--------------------| ------------------------------------------------------------|
|HOME                | C:\Source\Repos\jira-automated-testing                      |
|CONFIG              | C:\Program Files\Python310\Lib\site-packages\behavex\conf_behavex.cfg|
|OUTPUT              | C:\Source\Repos\jira-automated-testing\output               |
|TAGS                | None                                                        |
|PARALLEL_SCHEME     | scenario                                                    |
|PARALLEL_PROCESSES  | 1                                                           |
|TEMP                | C:\Source\Repos\jira-automated-testing\output\temp          |
|LOGS                | C:\Source\Repos\jira-automated-testing\output\outputs\logs  |
|LOGGING_LEVEL       | INFO                                                        |
|--------------------| ------------------------------------------------------------|

There are no failing test scenarios to run.

C:\Source\Repos\jira-automated-testing>behavex -rf
|--------------------| ------------------------------------------------------------|
|ENV. VARIABLE       | VALUE                                                       |
|--------------------| ------------------------------------------------------------|
|HOME                | C:\Source\Repos\jira-automated-testing                      |
|CONFIG              | C:\Program Files\Python310\Lib\site-packages\behavex\conf_behavex.cfg|
|OUTPUT              | C:\Source\Repos\jira-automated-testing\output               |
|TAGS                | None                                                        |
|PARALLEL_SCHEME     | scenario                                                    |
|PARALLEL_PROCESSES  | 1                                                           |
|TEMP                | C:\Source\Repos\jira-automated-testing\output\temp          |
|LOGS                | C:\Source\Repos\jira-automated-testing\output\outputs\logs  |
|LOGGING_LEVEL       | INFO                                                        |
|--------------------| ------------------------------------------------------------|

The path "C:\Source\Repos\jira-automated-testing\features\Create" was not found.

'15:47:39 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\features\Create" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\CHG\Different" was not found.

'15:47:39 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\CHG\Different" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\Tabs" was not found.

'15:47:39 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\Tabs" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\for" was not found.

'15:47:39 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\for" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\different" was not found.

'15:47:39 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\different" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\Change" was not found.

'15:47:39 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\Change" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\Categories.feature" was not found.

'15:47:39 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\Categories.feature" was not found.
'
InvalidFilenameError: C:/Source/Repos/jira-automated-testing/features/Create
Exit code: 0

C:\Source\Repos\jira-automated-testing>behavex -rf
|--------------------| ------------------------------------------------------------|
|ENV. VARIABLE       | VALUE                                                       |
|--------------------| ------------------------------------------------------------|
|HOME                | C:\Source\Repos\jira-automated-testing                      |
|CONFIG              | C:\Program Files\Python310\Lib\site-packages\behavex\conf_behavex.cfg|
|OUTPUT              | C:\Source\Repos\jira-automated-testing\output               |
|TAGS                | None                                                        |
|PARALLEL_SCHEME     | scenario                                                    |
|PARALLEL_PROCESSES  | 1                                                           |
|TEMP                | C:\Source\Repos\jira-automated-testing\output\temp          |
|LOGS                | C:\Source\Repos\jira-automated-testing\output\outputs\logs  |
|LOGGING_LEVEL       | INFO                                                        |
|--------------------| ------------------------------------------------------------|

The path "C:\Source\Repos\jira-automated-testing\"features\Create" was not found.

'15:48:16 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\"features\Create" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\CHG\Different" was not found.

'15:48:16 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\CHG\Different" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\Tabs" was not found.

'15:48:16 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\Tabs" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\for" was not found.

'15:48:16 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\for" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\different" was not found.

'15:48:16 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\different" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\Change" was not found.

'15:48:16 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\Change" was not found.
'

The path "C:\Source\Repos\jira-automated-testing\Categories.feature" was not found.

'15:48:16 - bhx_parallel - INFO -
The path "C:\Source\Repos\jira-automated-testing\Categories.feature" was not found.
'
ConfigError: No steps directory in 'C:\\Source\\Repos\\jira-automated-testing\\"features\\Create'
Exit code: 0

C:\Source\Repos\jira-automated-testing>

**Comment by hrcorval** [comment] 2022-05-16 22:27
We will review this functionality, as the implementation got outdated after a refactoring, and we will make this to run again. Sorry for any inconvenience...

**Comment by hrcorval** [comment] 2022-05-19 12:38
We see the problem is when having blank spaces in either, the path or the filename. There are no other conditions that cause this issue. We will be working on a fix. Thanks!

**Comment by hrcorval** [comment] 2022-05-19 18:16
Fixed in upcoming BehaveX version (>1.5.9)

**Comment by hrcorval** [comment] 2022-05-20 21:54
Issue fixed in BehaveX 1.5.10. 
Also, please review the documentation or argument help description, as we did a change to make the functionality to be more flexible, and now we need to provide the path to the failing scenarios filename as part of the --rerun-failures argument.
We are not expecting to do changes that break backward compatibility, so unless we are fixing a bug, this one should be the last change of this kind.

**Closed** 2022-05-20 21:54 UTC
Labels: bug
