### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'logging_format'

### ISSUE THREAD

**Issue by databene** [hrcorval/behavex#138] opened 2024-08-21 09:28 UTC
**Describe the bug**
Got this error message : AttributeError: 'Config' object has no attribute 'logging_format'
Stacktrace : 

> 18:20:28 File "/usr/local/lib/python3.8/site-packages/behavex/runner.py", line 511, in _launch_behave
18:20:28 execution_code = behave_script.main(behave_args)
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/main.py", line 183, in main
18:20:28 return run_behave(config)
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/main.py", line 127, in run_behave
18:20:28 failed = runner.run()
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/runner.py", line 804, in run
18:20:28 return self.run_with_paths()
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/runner.py", line 824, in run_with_paths
18:20:28 return self.run_model()
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/runner.py", line 626, in run_model
18:20:28 failed = feature.run(self)
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/model.py", line 321, in run
18:20:28 failed = scenario.run(runner)
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/model.py", line 1114, in run
18:20:28 failed = scenario.run(runner)
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/model.py", line 758, in run
18:20:28 runner.run_hook("after_scenario", runner.context, self)
18:20:28 File "/usr/local/lib/python3.8/site-packages/behavex/environment.py", line 68, in run_hook
18:20:28 behavex_env.after_scenario(context, *args)
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/log_capture.py", line 218, in f
18:20:28 h = LoggingCapture(context.config, level=level)
18:20:28 File "/usr/local/lib/python3.8/site-packages/behave/log_capture.py", line 68, in init
18:20:28 if config.logging_format:
18:20:28 AttributeError: 'Properties' object has no attribute 'logging_format'

**To Reproduce**
I try to run behavex in a docker container inside a Jenkins pipeline.
Example of command : 
behavex -t @testtag --parallel-processes 4 --parallel-scheme scenario
or
behavex -o ../report -t=@no-parallel ./features/feature1.feature ./features/feature2.feature ./features/feature3.feature

Discussion about this error : https://github.com/hrcorval/behavex/discussions/105#discussion-5570534

**Comment by hrcorval** [comment] 2024-09-06 16:10
Hi @databene, despite we were not able to reproduce the bug locally, we understand the problem was in the order in which behavex hooks were executed in the behavex environment.py module:

<img width="674" alt="image" src="https://github.com/user-attachments/assets/a0ff4c69-0a9b-4c6f-a8d5-49290ee872a8">

Please, let us know if this issue got fixed in latest BehaveX version (v4.0.2). Otherwise, we will keep investigating about this issue

**Closed** 2024-09-12 14:59 UTC
Labels: Answered, fixed
